# Generated by Django 4.2.11 on 2024-04-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox1', models.BooleanField(default=False)),
                ('checkbox2', models.BooleanField(default=False)),
                ('checkbox3', models.BooleanField(default=False)),
                ('checkbox4', models.BooleanField(default=False)),
                ('checkbox5', models.BooleanField(default=False)),
                ('checkbox6', models.BooleanField(default=False)),
            ],
        ),
    ]
